---
apiVersion: v2
type: application
name: gotify
description: a simple server for sending and receiving messages
version: 1.2.8
appVersion: 2.6.1
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/gotify-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://gotify.net/
keywords:
  - gotify
  - notification
sources:
  - https://github.com/gotify/server
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
