---
apiVersion: v2
type: application
name: freshrss
description: A WebUI to read article via RSS
version: 1.2.10
appVersion: 1.24.3
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/freshrss-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://www.freshrss.org/
keywords:
  - freshrss
  - rss
sources:
  - https://github.com/FreshRSS/FreshRSS
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
