---
apiVersion: v2
type: application
name: jellyfin
description: Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media
version: 1.1.7
appVersion: "10.9.11"
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/jellyfin-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://jellyfin.org/
keywords:
  - media server
  - Plex
  - Jellyfin
  - Media
  - Streaming
  - Server
sources:
  - https://github.com/jellyfin/jellyfin
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
