---
apiVersion: v2
type: application
name: mylar3
description: Mylar3 is an automated Comic Book (cbr/cbz) downloader program
version: 0.1.0
appVersion: 2021.12.13
icon: https://mylarcomics.com/img/mylarlogo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://mylarcomics.com/
keywords:
  - mylar3
  - mylar
  - comic
  - cbr
  - cbz
  - downloader
sources:
  - https://github.com/mylar3/mylar3
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.5.0
