---
apiVersion: v2
type: application
name: glance
description: A self-hosted dashboard that puts all your feeds in one place
version: 0.1.0
appVersion: v0.7.4
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
    url: https://une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://github.com/glanceapp/glance
keywords:
  - dashboard
  - feeds
  - rss
sources:
  - https://github.com/glanceapp/glance
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.5.0
