---
apiVersion: v2
type: application
name: linkding
description: linkding is a bookmark manager that you can host yourself. It's designed be to be minimal, fast, and easy to set up.
version: 1.1.15
appVersion: "1.34.0"
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/linkding-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://github.com/sissbruecker/linkding
keywords:
  - linkding
  - bookmark manager
sources:
  - https://github.com/sissbruecker/linkding
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
