---
apiVersion: v2
type: application
name: flaresolverr
description: "FlareSolverr is a proxy server that solves Cloudflare's Javascript challenges."
version: 0.1.0
appVersion: "v3.3.21"
# icon:
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://github.com/FlareSolverr/FlareSolverr
keywords:
  - FlareSolverr
  - Cloudflare
  - Proxy
sources:
  - https://github.com/FlareSolverr/FlareSolverr
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.5.0
