---
apiVersion: v2
type: application
name: uptime-kuma
description: Uptime Kuma is an easy-to-use self-hosted monitoring tool.
version: 1.2.0
appVersion: 1.23.15
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/uptime-kuma-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://github.com/louislam/uptime-kuma
keywords:
  - monitoring
  - uptime
  - kuma
sources:
  - https://github.com/louislam/uptime-kuma
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.5.0
