---
apiVersion: v2
type: application
name: jackett
description: "Jackett works as a proxy server: it translates queries from apps into tracker-site-specific http queries."
version: 1.3.0
appVersion: "0.22.1085"
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/jackett-logo.png
maintainers:
 - name: QJOLY
   email: github@une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://github.com/Jackett/Jackett
keywords:
 - Jackett
 - Plex
 - Series
sources:
 - https://github.com/Jackett/Jackett
dependencies:
 - name: common
   repository: https://rubxkube.github.io/common-charts
   version: v0.3.12
