---
apiVersion: v2
type: application
name: baikal
description: Baikal is a Cal and CardDAV server, based on sabre/dav, that includes an administrative interface for easy management.
version: 1.2.6
appVersion: '0.10.1-nginx'
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/baikal-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://sabre.io/baikal/
keywords:
  - baikal
sources:
  - https://github.com/sabre-io/Baikal
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
