---
apiVersion: v2
type: application
name: radarr
description: Radarr is a movie collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
version: 1.1.7
appVersion: "5.15.1"
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/radarr-logo.png
maintainers:
 - name: QJOLY
   email: github@une-tasse-de.cafe
kubeVersion: ">= 1.18"
home: https://radarr.video/
keywords:
 - Radarr
 - Movies
 - Plex
sources:
 - https://github.com/Radarr/Radarr
dependencies:
 - name: common
   repository: https://rubxkube.github.io/common-charts
   version: v0.2.2
