---
apiVersion: v2
name: memo
description: Memo (A privacy-first, lightweight note-taking service)
type: application
version: 1.1.7
appVersion: "0.19"
keywords:
 - memo
home: https://usememos.com/
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/memo-logo.png
maintainers:
 - email: github@une-tasse-de.cafe
   name: QJOLY
   url: https://une-tasse-de.cafe
sources:
 - https://github.com/usememos/memos
dependencies:
 - name: common
   repository: https://rubxkube.github.io/common-charts
   version: v0.2.2
