---
apiVersion: v2
type: application
name: vaultwarden
description: Vaultwarden is an easy-to-use self-hosted password manager.
version: 1.1.13
appVersion: 1.32.6
icon: https://raw.githubusercontent.com/RubxKube/charts/main/img/vaultwarden-logo.png
maintainers:
  - name: QJOLY
    email: github@une-tasse-de.cafe
kubeVersion: '>= 1.18'
home: https://github.com/dani-garcia/vaultwarden
keywords:
  - password manager
  - vaultwarden
sources:
  - https://github.com/dani-garcia/vaultwarden
dependencies:
  - name: common
    repository: https://rubxkube.github.io/common-charts
    version: v0.2.2
